name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DATABASE_URL,SECRET_KEY,ALLOWED_ORIGINS,SMTP_USER,SMTP_PASS,SMTP_TO
          script: |
            cd ~/portfolio
            git pull
            cat > backend/.env << EOF
            DATABASE_URL=$DATABASE_URL
            SECRET_KEY=$SECRET_KEY
            ALLOWED_ORIGINS=$ALLOWED_ORIGINS
            SMTP_HOST=smtp.gmail.com
            SMTP_PORT=587
            SMTP_SSL=false
            SMTP_USER=$SMTP_USER
            SMTP_PASS=$SMTP_PASS
            SMTP_TO=$SMTP_TO
            EOF
            docker compose up -d --build